### ISSUE TITLE
Add sustainability tips back into the game

### ISSUE THREAD

**Issue by AustinLeavitt** [TrashTossTeam8/TrashToss#50]
For some reason we lost that when working with GitHub.

**Comment by AustinLeavitt** [comment]
Sustainability tips should appear when the user sorts trash incorrectly.

**Comment by SmileAndXuan** [comment]
Bug fixed, it would appear when the user sort trash incorrectly, but it will appear for the next incorrectly sort, so should i make it appear for a time limit or is it ok just left it like it?

**Comment by AustinLeavitt** [comment]
It should disappear after maybe ten seconds or so.

**Comment by AustinLeavitt** [comment]
Added tips back into the game. The tip object was in the wrong location. I also went through and added specific tips for each waste object so that if the user sorts their trash incorrectly, the user is told what they did wrong. If the user misses the bins entirely, the tips simply tell them what bin they belonged to. This was accomplished by collecting info on the objects that collide with the floor.
