### ISSUE TITLE
Test the game

### ISSUE THREAD

**Issue by AustinLeavitt** [TrashTossTeam8/TrashToss#57]

**Comment by AustinLeavitt** [comment]
This will be done by following the test specifications during our user testing sessions.

**Comment by Amalazing** [comment]
Our tests went over well, most people just thought that the game was too difficult

**Comment by AustinLeavitt** [comment]
People thought the game was too hard, and found a couple of bugs that have since been resolved. Overall people had positive things to say about our game.
