### ISSUE TITLE
Take more notes during meetings

### ISSUE THREAD

**Issue by AustinLeavitt** [TrashTossTeam8/TrashToss#70]
Dr. Birgit Penzenstadler said we should be taking more notes during our weekly meetings and discussions.

**Comment by Amalazing** [comment]
I see that both Mamadou and Austin are doing it on laptops. I will start next meeting.

**Comment by AustinLeavitt** [comment]
We've been better about taking notes and documenting since we opened this issue. I'm more organized now than I was at the start of this semester.
