### ISSUE TITLE
Fix the collision box on the waste bins.

### ISSUE THREAD

**Issue by AustinLeavitt** [TrashTossTeam8/TrashToss#83]
The bins have been switched, but the landfill bin accepts recyclables etc.

**Comment by AustinLeavitt** [comment]
Correction: This is only for the AR version of the game. The offline mode works as intended.

**Comment by Amalazing** [comment]
I was trying to re-create this but I think it was specific to certain trash objects and not the waste bin itself

**Comment by AustinLeavitt** [comment]
After looking at this problem again it turns out Lawrence is correct. Certain objects were assigned to the wrong bin, the bins were fine themselves. I went back and made sure they were all assigned to the correct bin. Moving this to done.
