### ISSUE TITLE
Add a new ground to offline mode.

### ISSUE THREAD

**Issue by AustinLeavitt** [TrashTossTeam8/TrashToss#89]
Currently the floor of the offline mode is the default beige floor. Should be something more visually pleasing

**Comment by Amalazing** [comment]
I have added a background picture in the new non AR mode. Gonna throw in some grass for the ground soon

**Comment by AustinLeavitt** [comment]
I added some grass to the ground. Got the texture from the Unity Asset Store for free. Looks a lot better now.
